### ISSUE TITLE
Distributed mode tests constantly being skipped

### ISSUE THREAD

**Issue by Schachte** [minio/warp#358]
I'm having issues where my distributed load tests are being skipped and I'm not sure why, but I've include details below.

- Clocks are synced
- Running on Google Cloud
- All ports/ips are open and can ping between machines
- Running the client and server within a docker container, but I'm mounting /etc/localtime and /etc/timezone into the container.

I'm running some distributed load tests on GCP with the following config on the server node.

```yml
warp:
  api: v1
  benchmark: put
  json: true
  warp-client:
    - 10.168.0.20:7761
    - 10.168.0.21:7761
    - 10.168.0.22:7761

  remote:
    region: auto
    access-key: 'redacted'
    secret-key: 'redacted'
    host:
      - 'redacted'
    tls: true 
    bucket: 'warp-test'

  params:
    duration: 60s
    concurrent: 500
    obj:
      size: 1KiB
    no-clear: false
    keep-data: false

  io:
    disable-multipart: true
    md5: false

  analyze:
    verbose: true
```

I can `ping` all these hosts and I've confirmed via `nc -vz <ip> <port>` they are all open. Additionally, I'm looking at logs on each worker node and see:

```bash
warp: Listening on :7761
warp: Accepting connection from server: egilCsUU2MHmZxG4JnUM
warp: Executing put benchmark.
warp: Starting stage prepare in 999.470966ms
warp: prepare done...
warp: Waiting
warp: Starting stage benchmark in 2.99965753s
warp: Starting
warp: Stopping
warp: benchmark done...
warp: Benchmark data written to "warp-put-2025-01-07[002517]-ZojQyi.csv.zst"
warp: Starting stage cleanup in 0s
warp: Starting cleanup...
Clearing Prefix "warp8/nfAZd1Zy/"...warp: cleanup done...
warp: Received Disconnect
warp: Closing connection
```

However, the server node gets the following. Note the skipped stats and `skipped: true`

```json
{
  "type": "single",
  "operations": [
    {
      "throughput": {
        "start_time": "0001-01-01T00:00:00Z",
        "end_time": "0001-01-01T00:00:00Z",
        "errors": 0,
        "measure_duration_millis": 0,
        "average_bps": 0,
        "average_ops": 0,
        "operations": 0
      },
      "start_time": "0001-01-01T00:00:00Z",
      "end_time": "0001-01-01T00:00:00Z",
      "throughput_by_host": null,
      "type": "PUT",
      "host_names": null,
      "first_errors": null,
      "hosts": 0,
      "clients": 0,
      "concurrency": 0,
      "errors": 0,
      "objects_per_operation": 0,
      "n": 7543,
      "skipped": true
    }
  ],
  ````

What would cause this?
